# Atulya AI - Version List
# This file contains all available models and their versions

# System Version
system:
  version: "0.1.0"
  release_date: "2024-12-19"
  architecture: "Dynamic Intelligence System"
  next_major: "0.5.0"
  target_production: "1.0.0"

# Version Roadmap
roadmap:
  "0.1.0":
    status: "current"
    focus: "Core system foundation"
    features:
      - "Basic FastAPI server"
      - "DeepSeek R1 integration"
      - "Dynamic model loading framework"
      - "Basic memory system"
    
  "0.2.0":
    status: "planned"
    focus: "Bug fixes and stability"
    features:
      - "Fix LLM download issues"
      - "Improve error handling"
      - "Performance optimizations"
      - "Memory management fixes"
    
  "0.3.0":
    status: "planned"
    focus: "Enhanced reliability"
    features:
      - "Advanced error recovery"
      - "Better logging system"
      - "Configuration validation"
      - "Service stability improvements"
    
  "0.4.0":
    status: "planned"
    focus: "User experience improvements"
    features:
      - "Enhanced web UI"
      - "Better documentation"
      - "User feedback system"
      - "Accessibility improvements"
    
  "0.5.0":
    status: "planned"
    focus: "Major automation features"
    features:
      - "Full LLM download automation"
      - "Advanced task automation"
      - "Multi-agent coordination"
      - "Self-improvement capabilities"
    
  "1.0.0":
    status: "target"
    focus: "Production-ready release"
    features:
      - "Enterprise-grade stability"
      - "Complete automation suite"
      - "Advanced security features"
      - "Full documentation suite"

# Core Models
models:
  # Main Brain - DeepSeek R1
  deepseek-r1:
    version: "latest"
    model_id: "deepseek-ai/deepseek-r1"
    size: "~7GB"
    description: "Main brain for analysis, reasoning, and delegation"
    use_case: "general"
    priority: 1
    status: "stable"
    
  # Vision Models
  blip-large:
    version: "latest"
    model_id: "Salesforce/blip-image-captioning-large"
    size: "~990MB"
    description: "Image captioning and visual question answering"
    use_case: "vision"
    priority: 2
    status: "stable"
    
  # Speech Models
  whisper-large:
    version: "large-v3"
    model_id: "large-v3"
    size: "~1.5GB"
    description: "Speech to text transcription"
    use_case: "speech_input"
    priority: 2
    status: "stable"
    
  coqui-tts:
    version: "latest"
    model_id: "tts_models/en/ljspeech/tacotron2-DDC"
    size: "~85MB"
    description: "Text to speech synthesis"
    use_case: "speech_output"
    priority: 2
    status: "stable"
    
  # Video Models
  videomae-base:
    version: "latest"
    model_id: "MCG-NJU/videomae-base"
    size: "~85MB"
    description: "Video analysis and classification"
    use_case: "video"
    priority: 3
    status: "experimental"
    
  # Document Models
  layoutlm-v3:
    version: "latest"
    model_id: "microsoft/layoutlmv3-base"
    size: "~500MB"
    description: "Document layout understanding"
    use_case: "document"
    priority: 3
    status: "experimental"
    
  # Audio Generation
  musicgen:
    version: "latest"
    model_id: "facebook/musicgen-small"
    size: "~300MB"
    description: "Music and audio generation"
    use_case: "audio_generation"
    priority: 4
    status: "experimental"
    
  # Embedding Models
  sentence-transformers:
    version: "latest"
    model_id: "sentence-transformers/all-MiniLM-L6-v2"
    size: "~90MB"
    description: "Text embeddings for search and memory"
    use_case: "embedding"
    priority: 1
    status: "stable"

# Tool Versions
tools:
  file_operations:
    version: "1.0.0"
    description: "File system operations"
    status: "stable"
    
  web_search:
    version: "1.0.0"
    description: "Web search and information retrieval"
    status: "stable"
    
  code_execution:
    version: "1.0.0"
    description: "Safe code execution environment"
    status: "stable"
    
  email_tools:
    version: "0.5.0"
    description: "Email management tools"
    status: "development"
    
  calendar_tools:
    version: "0.5.0"
    description: "Calendar and scheduling tools"
    status: "development"
    
  system_admin:
    version: "0.8.0"
    description: "System administration tools"
    status: "beta"

# Core Components
components:
  agent:
    version: "0.1.0"
    description: "Intelligent agent coordinator"
    status: "stable"
    
  memory:
    version: "0.1.0"
    description: "Memory and embedding system"
    status: "stable"
    
  model_loader:
    version: "0.1.0"
    description: "Dynamic model loading system"
    status: "stable"
    
  voice:
    version: "0.1.0"
    description: "Voice processing system"
    status: "stable"
    
  config_manager:
    version: "0.1.0"
    description: "Configuration management system"
    status: "stable"

# Dependencies
dependencies:
  python: "3.8+"
  fastapi: "0.104.0+"
  transformers: "4.35.0+"
  torch: "2.0.0+"
  chromadb: "0.4.0+"
  sentence_transformers: "2.2.0+"
  openai_whisper: "20231117+"
  TTS: "0.22.0+"
  pydantic: "2.0.0+"
  uvicorn: "0.24.0+"

# Installation Notes
installation:
  initial_size: "~50MB"
  total_potential_size: "~10GB"
  dynamic_loading: true
  auto_cleanup: true
  memory_efficient: true

# Release Priorities
priorities:
  critical:
    - "Fix LLM download issues"
    - "Improve error handling"
    - "Memory management optimization"
  
  high:
    - "Advanced automation features"
    - "Multi-agent coordination"
    - "Self-improvement capabilities"
  
  medium:
    - "Enhanced web UI"
    - "Better documentation"
    - "User feedback system"
  
  low:
    - "Accessibility improvements"
    - "Advanced security features"
    - "Enterprise integrations" 